### ISSUE TITLE
Not able to see the Channels List

### ISSUE THREAD

**Issue by mobeendev** [GetStream/react-native-chat-tutorial#1]
**Describe the bug**
Can not see the channel list.

**Dev environment info (please complete/provide the following information):**

{
  "name": "ReactNativeChatTutorial",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/cameraroll": "^4.0.2",
    "@react-native-community/netinfo": "^5.9.10",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "@stream-io/flat-list-mvcp": "^0.0.5",
    "global": "^4.4.0",
    "react": "16.13.1",
    "react-devtools": "^4.10.1",
    "react-native": "0.63.4",
    "react-native-document-picker": "^5.0.0",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.10.1",
    "react-native-haptic-feedback": "^1.11.0",
    "react-native-image-crop-picker": "^0.36.0",
    "react-native-image-resizer": "^1.4.3",
    "react-native-reanimated": "2.0.0-rc.0",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.17.1",
    "react-native-share": "^5.1.1",
    "react-native-svg": "^12.1.0",
    "stream-chat-react-native": "^3.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.16",
    "@babel/runtime": "^7.12.13",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.20.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.65.1",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**To Reproduce**

I just cloned the app

Channel list show appear so that I can do 1-on-1 chat.

**Screenshots**
![image](https://user-images.githubusercontent.com/10846423/116225190-36031900-a75a-11eb-9b0c-a30928828940.png)

**Comment by vishalnarkhede** [comment]
Hey @mobeendev you will need to populate some data on your API_KEY. You can use out test-data-cli tool for that purpose - https://github.com/GetStream/stream-chat-test-data-cli

**Comment by mobeendev** [comment]
@vishalnarkhede thanks for above.
I setup the cli and able to run it. 

now if I use any user fro the created users list, I get follow error:

![image](https://user-images.githubusercontent.com/10846423/116372356-0238f980-a815-11eb-966c-d1b2f7a46ef8.png)
I am using this user :
![image](https://user-images.githubusercontent.com/10846423/116372499-1ed53180-a815-11eb-93b6-24ad495ddab9.png)
Here's the setting in app:

![image](https://user-images.githubusercontent.com/10846423/116372572-344a5b80-a815-11eb-8d68-103701d031e1.png)

**Comment by mobeendev** [comment]
@vishalnarkhede I was able to connect after some time, I think the server was taking time to update the user.

**Comment by vishalnarkhede** [comment]
hmm thats wierd. But anyways, we will look into that, and I will close this issue for now!!
